-- CreateEnum
CREATE TYPE "ParadaTipo" AS ENUM ('OPERACIONAL', 'NAO_OPERACIONAL');

-- CreateEnum
CREATE TYPE "ParadaCategoria" AS ENUM ('MANUTENCAO_CORRETIVA', 'MANUTENCAO_PREVENTIVA', 'SETUP_TROCA_FERRAMENTA', 'FALTA_MATERIAL', 'QUALIDADE_INSPECAO', 'AJUSTE_PROCESSO', 'ABASTECIMENTO', 'LIMPEZA', 'ALMOCO', 'BANHEIRO', 'REUNIAO', 'TREINAMENTO', 'DDS', 'OUTROS_NAO_OPERACIONAL');

-- AlterTable
ALTER TABLE "Parada" ADD COLUMN     "categoria" "ParadaCategoria",
ADD COLUMN     "tipo" "ParadaTipo" NOT NULL DEFAULT 'OPERACIONAL';
